### ISSUE TITLE
Docs - ApplicationSession: methods and lifecycle

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#203]
"""
I have been playing with ApplicationSession and I encounter many methods that are automatically called during the application life cycle such as onConnect, onJoin, onLeave, onDisconnect, etc.

It can be hard to understand which one does what (even with the docs on hand, lots of new concepts here), but more importantly, when.

A schema of the application life cycle, including what method is called step by step would be very helpful. Some explanations about what I can and _can't_ do as as an application developper in each of these methods would also be super useful. Bonus if we can see that life cycle in context in the reactor/asyncio main loop lifecycle and how it interacts with it. Extra bonus for contexte in crossbar.io.

I couldn't find one in the documentation, but I could have missed it. If I did, I apologize. If not, I'm begging for one. I do, once again, understand this is a lot of work, so I won't take offense if it's not possible. Quick and dirty ASCII art will do. I can even turn it into a clean vectorial one if you want to contribute a little bit to the documentation.
"""

**Comment by oberstet** [comment]
Documented now: http://autobahn.ws/python/wamp/programming.html#session-lifecycle

**Comment by eranimo** [comment]
Thank you. I think examples how to do simple password-based authentication using WAMP and sending events to specific clients (like in a chat client) would be very helpful as well.
