### ISSUE TITLE
Refactor FutureMixin

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#242]
https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/asyncio/wamp.py#L52
https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/twisted/wamp.py#L50

1. Rename class to `LoopMixin`
2. Move to `autobahn.twisted.util` / `autobahn.asyncio.util`
3. Make static methods public
4. Add proper docstrings

**Comment by meejah** [comment]
This can be closed I think since the move to https://github.com/tavendo/txaio
