### ISSUE TITLE
Cleanup examples

### ISSUE THREAD

**Issue by goeddea** [tavendo/AutobahnPython#251]
this need only be minimal:

- one to two sentences explaining what the example is for
- link to how to run the examples (yes, same repo, higher up in the directory tree, but necessary if the visitor came via a direct link)
- links to relevant documentation

**Comment by oberstet** [comment]
improve docs like @goeddea describes, but also remove old, outdated examples, and in particular examples where we have newer and more complete ones in the crossbarexamples repo

**Comment by oberstet** [comment]
I have moved examples to crossbarexamples which no longer fit into here. The now remaining examples are all fine here. The examples use different idioms depending on when they were written. But that's fine for now. Cleanup is done.

Missing or incomplete README's: yes, absolutely. Maybe better in individual concrete issues ("README in Example XYZ sucks")
