### ISSUE TITLE
Implement RawSocket revision

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#291]
WAMP-over-RawSocket is implemented in AutobahnPython, but needs adjustment to the revised section in the spec: https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#rawsocket-transport

**Comment by oberstet** [comment]
implemented now

**Comment by ecorm** [comment]
I've just upgraded my Crossbar installation, and I'm pleased to report that raw socket handshaking works perfectly with CppWAMP. Thanks!

**Comment by oberstet** [comment]
@ecorm thanks for testing with CppWAMP and feedback!
