### ISSUE TITLE
Intercept exceptions

### ISSUE THREAD

**Issue by gak** [tavendo/AutobahnPython#302]
My ideal situation is to be able to:

* Declare a callback for when an exception is caught
* The callback can decide to modify the exception, or respond differently

I did write a hacky solution in a pull request which was understandably denied because it had problems: 0423e8b1e89fdef3bd06d657c0821d0c6c90ab9f

**Comment by oberstet** [comment]
this is now possible, pls see here http://autobahn.ws/python/reference/autobahn.wamp.html#autobahn.wamp.protocol.ApplicationSession.onUserError
