### ISSUE TITLE
Error while running an autobahn app on Windows

### ISSUE THREAD

**Issue by sametmax** [tavendo/AutobahnPython#307]
I ran the video with the remote control recently. It sill works on Linux, but on windows, you get : 

```
Failure: twisted.internet.error.ConnectError: An error occurred while connecting
: 10049:  The requested address is not valid in its context.
```

This happens only on Windows (was on Windows 8 64 bits, didn't try other flavours) if we use ws://0.0.0.0:port or ws://127.0.0.1:port as an URL. Using the public crossbar instance works.

**Comment by oberstet** [comment]
can't reproduce
