### ISSUE TITLE
Random error on disconnect

### ISSUE THREAD

**Issue by pristas-peter** [tavendo/AutobahnPython#308]
Sometimes when server(router) is quickly going up/down (testing flapping connection), this Exception raises on the client, I guess the session isn't ready when disconnect happens: 

Traceback (most recent call last):
  File "python3.4/site-packages/autobahn/wamp/websocket.py", line 75, in onClose
    self._session.onClose(wasClean)
AttributeError: 'WampWebSocketClientProtocol' object has no attribute '_session'

**Comment by meejah** [comment]
I haven't repeated this, but looking at the code I don't believe it's possible any longer...
