### ISSUE TITLE
Tornado integration

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnPython#314]
We have adapters for Twisted and asyncio for use with both WebSocket and WAMP.

Creating adapters for Tornado should be easy.

**Comment by sametmax** [comment]
Also, people who want the tornado API and use autobahn can do so by using cyclone, which let your run tornado on top of twisted.

**Comment by oberstet** [comment]
won't fix. we have enough to do;)

**Comment by cecilphillip** [comment]
I just came across his issue in google, hope for a different result ☹️ 
Looks like Tornado has some interop with Twisted already in place. Maybe it might be worth another look? https://github.com/tornadoweb/tornado/blob/8ea13db107f4d44fadd24578e693f2838012caa7/tornado/platform/twisted.py

**Comment by oberstet** [comment]
Yeah, `TornadoReactor` exists for a long time already - but this issue here was about the question whether we want to add _native_ support for Tornado, like we have for Twisted and asyncio. Autobahn runs natively on each of the former - it does _not_ use an asyncio-based Twisted reactor, or a Twisted based asyncio loop.

Doing the same for Tornado: unlikely that we'll change above decision.

**Comment by meejah** [comment]
@cecilphillip perhaps you can try the mailing-list or IRC and explain what you're trying to do? You should, e.g., be able to use Tornado as a component inside crossbar to serve Web requests etc without any problems. This ticket was about using the Tornado event-loop directly (IIUC).
