### ISSUE TITLE
Exception when TCP connection closes before websocket connection is established

### ISSUE THREAD

**Issue by rafzi** [tavendo/AutobahnPython#316]
In onClose in file

https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/wamp/websocket.py

self._session.onClose(wasClean) is called, but it is possible that the _session is not existing yet.

We encountered this when the TCP connection was aborted because of an SSL certificate error. This traceback was pretty misleading in finding the actual error.

A fix could be checking if a _session exists or at a higher level control when onClose is called.

**Comment by oberstet** [comment]
You mean this line: https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/wamp/websocket.py#L75 ?

That is, `self._session.onClose` is being called, but `self._session` is `None`, because the session was never established in the first place?

**Comment by rafzi** [comment]
Yes, I meant that one. self._session.onOpen was a typo.

**Comment by rafzi** [comment]
It's not None, it just was not defined yet. The exception is:

AttributeError: WampWebSocketServerProtocol instance has no attribute '_session'

An easy reproduction I found: Connect to the websocket url via http(s). The website that displays "I am not Web server, but a WebSocket Endpoint.".

**Comment by oberstet** [comment]
I ses. Could you check if the fix works?

**Comment by rafzi** [comment]
That fixes it. Thank you for the quick response!

**Comment by oberstet** [comment]
great! thx for verifying
