### ISSUE TITLE
array.tostring() generates warning on Python 3.3

### ISSUE THREAD

**Issue by hlamer** [tavendo/AutobahnPython#319]
/usr/local/lib/python3.3/dist-packages/autobahn/websocket/protocol.py:2084: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

`tostring` is used in xormasker.py

**Comment by oberstet** [comment]
Python 2 has no `tobytes`

**Comment by oberstet** [comment]
The docs mention the deprecation (https://docs.python.org/3/library/array.html#array.array.tostring), but there is no deprecation warning with Python 3.4:

```console
$ python3
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:24:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from test import test
b'sdfsd'
```

test.py:

```python
from array import array

def test():
   payload = array('B', b"sdfsd")
   print(payload.tostring())

test()
```

**Comment by hlamer** [comment]
I see this warning when running unit tests
```python
from array import array
import unittest

class Test(unittest.TestCase):
    def test_1(self):
       payload = array('B', b"sdfsd")
       print(payload.tostring())

unittest.main()
```

or just use `python3 -W default test.py`
