### ISSUE TITLE
utf8validateIncomingCurrentMessage is undefined

### ISSUE THREAD

**Issue by robertrottermann** [tavendo/AutobahnPython#321]
autobahn/websocket/protocol.py uses utf8validateIncomingCurrentMessage on line 1564, which is potentially undefined, as it will only be defined when processDataHixie76 is called with self.inside_message set.

**Comment by oberstet** [comment]
For Hybi-mode, this is set here: https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/websocket/protocol.py#L1857
