### ISSUE TITLE
Exception when connection closes

### ISSUE THREAD

**Issue by rafzi** [tavendo/AutobahnPython#323]
> WAMP-over-WebSocket transport lost: wasClean = False, code = 1006, reason = 'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/websocket.py", line 77, in onClose
    self._session.onClose(wasClean)
TypeError: onClose() takes exactly 1 argument (2 given)

Sorry for not opening a PR. I was unable to find the onClose that is called here.

**Comment by oberstet** [comment]
Did you override `ApplicationSession.onClose`? Since the base class code does take 2 arguments: https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/wamp/protocol.py#L746

**Comment by rafzi** [comment]
Yes, sorry it was overridden in an obscure way.

**Comment by oberstet** [comment]
No problem. Glad you found the issue.
