### ISSUE TITLE
Make application choose between loose and strict URIs

### ISSUE THREAD

**Issue by Paranaix** [tavendo/AutobahnPython#325]
As the specification does not make strict URIs mandatory, developers shall be able to freely choose which scheme to use. If their architecture can work with loose URIs, a stricter convention should not be imposed on them. Enabling the user to choose could easily be achieved by adding a "strict" parameter to the URI constructor which defaults to True.

**Comment by oberstet** [comment]
I think there is a flag somewhere to control that behavior. Need to make sure this is fully working and documented

**Comment by oberstet** [comment]
migrated to https://github.com/crossbario/crossbar/issues/441
