### ISSUE TITLE
SerializationError does not result in a message

### ISSUE THREAD

**Issue by Paranaix** [tavendo/AutobahnPython#327]
This might relate to https://github.com/crossbario/crossbar/pull/218

If a serialization error is thrown when an endpoint returned an invalid object, no error message is sent to the caller, the call stays open forever without result.

**Comment by agronholm** [comment]
Isn't this the same as #349?

**Comment by Paranaix** [comment]
Yes, notice that this issue was opened long before. Probably an oversight
