### ISSUE TITLE
Enable registration of event handlers which are generators

### ISSUE THREAD

**Issue by deceze** [tavendo/AutobahnPython#332]
In a properly distributed application, it's likely that one event handler may want to call another, e.g.:

```python
@subscribe('foo')
def bar(self):
    data = self.call('baz')
```

At the moment this is not that simple, since `self.call` returns a Future, which needs to be resolved manually, which clutters up the code. The alternative:

```python
@subscribe('foo')
@coroutine
def bar(self):
    data = yield from self.call('baz')
```

This doesn't work either, since the resulting coroutine is never scheduled to run by autobahn.

My current workaround is this:

```python
def subscribe_coro(uri, loop=None):
    def decorator(f):
        @subscribe(uri)
        @wraps(f)
        def wrapper(*args, **kwargs):
            coro = f(*args, **kwargs)
            asyncio.async(coro, loop=loop)
        return wrapper
    return decorator

@subscribe_coro('foo')
@coroutine
def bar(self):
    data = yield from self.call('baz')
```

It'd be nice if something like this would be integrated into autobahn itself.

**Comment by Paranaix** [comment]
Actually using @coroutine should work; atleast @inlineCallbacks works just fine. As far as I know @coroutine works pretty much identically to @inlineCallbacks and is supposed to return a Future.

**Comment by oberstet** [comment]
This should work - in both Twisted and asyncio. If not, it's a bug. I will cook up an example ..

**Comment by deceze** [comment]
It does sound like a bug then. For reference, here's (parts of) the actual code:

```python
from autobahn.asyncio import wamp
from autobahn.wamp import subscribe
from asyncio import coroutine

class Controller(wamp.ApplicationSession):
    def onConnect(self):
        # ...

    def onJoin(self, details):
        yield from self.register(self)
        yield from self.subscribe(self)

class ACDController(Controller):
    @subscribe('wamp.metaevent.session.on_join')
    @coroutine
    def operator_registration(self, session: dict):
        if session['authrole'] != 'operator':
            return

        details = yield from self.call('foo.bar.authenticator.details', session['authid'])
        # more operations here

        logging.debug('Operator added to pool: {}'.format(operator))
```

I have run this every which way, using log statements, debuggers with breakpoints, even code coverage... the code is simply not being executed.

**Comment by deceze** [comment]
For what it's worth, this seems to work fine for registered RPC methods, but not for subscription handlers.

**Comment by oberstet** [comment]
http://stackoverflow.com/questions/28293198/calling-a-remote-procedure-from-a-subscriber-and-resolving-the-asyncio-promise

**Comment by meejah** [comment]
I believe PR #397 should have improved this behavior for subscribed methods; @deceze can you confirm if your use-case works now, with latest Autobahn (you'll have to use master, this isn't in a released version yet).
