### ISSUE TITLE
A TOC for examples

### ISSUE THREAD

**Issue by Vayel** [tavendo/AutobahnPython#346]
At that [level](https://github.com/tavendo/AutobahnPython/tree/master/examples/asyncio/wamp), a list of all examples and what they do would help us a lot. Simply using the docstrings of the classes would be sufficient. For example:

# Examples of WAMP with asyncio

* **basic:** short description
    * **rpc:** short description
        * **decorators:** an application component registering RPC endpoints using decorators.

**Comment by oberstet** [comment]
we have that now:

* http://autobahn.ws/python/wamp/examples.html
* http://autobahn.ws/python/websocket/examples.html
