### ISSUE TITLE
Improve site contents

### ISSUE THREAD

**Issue by Vayel** [tavendo/AutobahnPython#351]
Tutorials are hard to find. [That page](http://autobahn.ws/python/contents.html) should be more visible. Something as on Crossbar.io Web site would be far better. A "Documentation" link would help.

Moreover, the TOC should contain a little text, as done [here](http://crossbar.io/docs/).

**Comment by oberstet** [comment]
fixed. pls see http://autobahn.ws/python/index.html#documentation-overview
