### ISSUE TITLE
ApplicationSession.connect() and .join() should return Futures/Deferreds

### ISSUE THREAD

**Issue by agronholm** [tavendo/AutobahnPython#360]
I can do this by overriding onOpen() and onJoin() but it's awkward that way. This should be a low hanging fruit. The only open question is whether the future/deferred should be resolved before or after calling the existing callbacks.

**Comment by agronholm** [comment]
Why is this needed? Consider a test client that connects to a router. I need some way to wait until the client has joined the realm until I start calling remote methods or publishing/subscribing to topics.

**Comment by agronholm** [comment]
It would of course be preferable if one could do testing within a single process, without an external router process but I don't see any way to do that right now.

**Comment by oberstet** [comment]
If `ApplicationSession.connect()` returned a Deferred/Future, auto-reconnecting (which we want to have) is becoming harder, since with the current API, we simply can fire the `onOpen` callback multiple times.
