### ISSUE TITLE
wampapp and klein: 'standalone=True' causes error

### ISSUE THREAD

**Issue by ralphstone** [tavendo/AutobahnPython#361]
hi, as per subject, the current examples for wampapp and klein have the Application parameter 'standalone=true' which causes an abort. the Application class seems to have a 'start_reactor' parameter instead. has there been a change to how wampapp's should be called within a klein route?

**Comment by goeddea** [comment]
The blog post about WAMP & Klein assumes an older version of Autobahn|Python which still contained a basic WAMP router.

Crossbar.io was extending this router. Architectural considerations for upcoming changes meant that this basic router was removed. You need to use another WAMP router now. We suggest Crossbar.io, but others should work as well.

**Comment by ralphstone** [comment]
thanks very much alexander. we are using crossbar as the router, and wish to call methods registered with crossbar, from python. have i missed something,  is there a new autobahn-crossbar library?  how should i be connecting to crossbar and calling a method from python now? i have been using this pattern within a klein py:

from autobahn.twisted.wamp import Application...
wampapp=Application()...
result=wampapp.session.call(...)...
if __main etc
......wampapp.run("ws://....")

**Comment by oberstet** [comment]
Remove the `standalone` argument and provide the URL of an externally running WAMP router, such as Crossbar.io
