### ISSUE TITLE
twisted 11 compat

### ISSUE THREAD

**Issue by tardyp** [tavendo/AutobahnPython#364]
buildbot supports twisted 11, and there is a silly import error with autobahn-python:

https://travis-ci.org/buildbot/buildbot/builds/54691826

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/autobahn-0.10.1-py2.6.egg/autobahn/twisted/util.py", line 30, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address, UNIXAddress
exceptions.ImportError: cannot import name IPv6Address

**Comment by oberstet** [comment]
@tardyp should work ..

**Comment by tardyp** [comment]
when do you intend to create a release including this fix?
I think we should wait this release before pushing https://github.com/buildbot/buildbot/pull/1603

**Comment by oberstet** [comment]
@tardyp Alright, released: https://pypi.python.org/pypi/autobahn/0.10.2
