### ISSUE TITLE
Allow customizing error details

### ISSUE THREAD

**Issue by siebz0r** [tavendo/AutobahnPython#365]
The [WAMP spec](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#call-error) mentions an error message can have a dict containing details about the error. Unfortunately Autobahn doesn't allow setting the details from an exception.

In ``autobahn.wamp.message.Error.marshal`` can be seen that the details dict is always empty.

Instead of leaving it always empty, allow a developer to pass a dict to an exception. That dict should end up in the actual error message. This allows for proper error messages and anything other than an URI.

**Comment by oberstet** [comment]
You can raise a `ApplicationError`: https://github.com/tavendo/AutobahnPython/blob/master/autobahn/wamp/exception.py#L200

**Comment by siebz0r** [comment]
Raising an `ApplicationError` doesn't suffice here. The `ApplicationError` only supports passing a URI, not a dict.

The specs define them separately:
```
[ERROR, CALL, CALL.Request|id, Details|dict, Error|uri, Arguments|list, ArgumentsKw|dict]
```

If an `ApplicationError` is converted to a WAMP error, the details dict will still be empty.

**Comment by oberstet** [comment]
It does support passing a dict. Just pass in keyword parameters

**Comment by siebz0r** [comment]
I see. But what is `details` for then? It seems redundant if keywords provide the same functionality.

**Comment by oberstet** [comment]
They don't. Please check out the WAMP spec ..
