### ISSUE TITLE
While trying to use reverse proxy with nginx, it fails

### ISSUE THREAD

**Issue by flyingrub** [tavendo/AutobahnPython#370]
if i want to connect to it normally it works fine.
but when i try to use it with nginx as reverse proxy it fails...
here is in my nginx conf : 
```
        location /door {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_pass http://127.0.0.1:9000;
        }
```

here is in my error log from nginx : 
```
upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.20, server: home, request: "GET /door HTTP/1.1", upstream: "http://127.0.0.1:9000/door", host: "pi:443"
``` 

i have [this](https://github.com/flyingrub/SSWOD/blob/master/server.py) : running on 127.0.0.1:9000

**Comment by flyingrub** [comment]
any explanation ?

**Comment by oberstet** [comment]
@flyingrub generally, questions are better addressed to the mailing list (https://groups.google.com/forum/#!forum/autobahnws) as this is for tracking issues. Nginx has specific support for WebSocket, and I guess this should be used, since what you do with your Nginx config above is still reverse proxying plain HTTP (I _think_, since I don't use much Nginx myself).

**Comment by flyingrub** [comment]
Thanks i will try with the mailing list

**Comment by flyingrub** [comment]
in fact i use an outdated version of nginx wich doesn't support this feature...

**Comment by oberstet** [comment]
@flyingrub Yep, you definitely need a version of Nginx with support for WebSocket. As noted above, "plain vanilla" HTTP proxy config won't cut it ..

If you care, you might help other by improving our docs

* https://github.com/crossbario/crossbarwww/blob/master/website/crossbario/docs/Reverse-Proxies.md

Is the source page for this doc page generated:

*http://crossbar.io/docs/Reverse-Proxies/

As you can see, it's quite empty;)

**Comment by flyingrub** [comment]
i don't want to steal :)
i found everything there : https://github.com/nicokaiser/nginx-websocket-proxy

**Comment by oberstet** [comment]
Oh, cool. I added the link .. thx! https://github.com/crossbario/crossbarwww/blob/master/website/crossbario/docs/Reverse-Proxies.md#nginx

**Comment by alt0** [comment]
you should add another parameter:
proxy_read_timeout 96000;

the default value is 60s
you will get a message "lost connect" after 60s idles with the default value
