### ISSUE TITLE
rawsocket protocol and WampRawSocketFactory mismatch

### ISSUE THREAD

**Issue by tigeraniya** [tavendo/AutobahnPython#376]
AutobahnPython/autobahn/twisted/rawsocket.py -> WampRawSocketFactory is expecting a list of serializers  whereas 

WampRawSocketServerFactory.__init__(self, factory, serializer, debug=debug) passes only one serializer . router is not starting due to this .

this makes it work , but i think is not right solution : 

class WampRawSocketFactory(Factory):
    """
    Base class for Twisted-based WAMP-over-RawSocket factories.
    """

    def __init__(self, factory, serializer=None, debug=False):
        """

        :param factory: A callable that produces instances that implement
            :class:`autobahn.wamp.interfaces.ITransportHandler`
        :type factory: callable
        :param serializers: A list of WAMP serializers to use (or None for default
           serializers). Serializers must implement
           :class:`autobahn.wamp.interfaces.ISerializer`.
        :type serializers: list
        """
        assert(callable(factory))
        self._factory = factory

        self.debug = debug

        if serializer is None:
            # try MsgPack WAMP serializer
            try:
                from autobahn.wamp.serializer import MsgPackSerializer
                serializer = MsgPackSerializer(batched=True)
                serializer = MsgPackSerializer()
            except ImportError:
                pass

        if serializer is None:
            # try JSON WAMP serializer
            try:
                from autobahn.wamp.serializer import JsonSerializer
                serializer = JsonSerializer(batched=True)
                serializer = JsonSerializer()
            except ImportError:
                pass

        if not serializer:
            raise Exception("could not import any WAMP serializers")

**Comment by oberstet** [comment]
this was work in progress ..
