### ISSUE TITLE
maxRetries reset upon successful connection?

### ISSUE THREAD

**Issue by indigolink** [tavendo/AutobahnPython#378]
The AutobahnPython/examples/twisted/websocket/echo_variants/client_reconnecting.py is very interesting but my issue is that the maxRetries is not 'reset' after a successful connection meaning that if for some reason during the lifetime execution of the script the connection is 'broken' 5 times it will stop whereas for me the ideal would be for the maxRetries to be 'reset' back to 5 after a successful connection from the client. Is this possible?

**Comment by meejah** [comment]
According to the Twisted docs, you need to call "resetDelay" on the factory. So you should be able to do ``self.factory.resetDelay()`` in the protocol's ``onOpen``, although I didn't test that.
