### ISSUE TITLE
Autobahn without crossbar.io

### ISSUE THREAD

**Issue by rtp-calpoly** [tavendo/AutobahnPython#385]
I have just started adapting my current architecture for a Django + pusher.com website to a more realtime-friendly application. I am wondering it Autobahn over asyncio can be run on its own without the need of any additional external routers/servers like crossbar.io (option suggested at the Autobahn's website).

**Comment by oberstet** [comment]
You can use AutobahnPython as a pure WebSocket library. When using WAMP, a router is always required. Btw: we have a mailing list;)
