### ISSUE TITLE
NameError in protocol.py

### ISSUE THREAD

**Issue by yacneyac** [tavendo/AutobahnPython#391]
I'm using Autobahn version  0.10.3

When I try call self.sendClose(code=3001, reason=u'some reason') I catch error.
 Last line in traceback:
  File "/usr/local/lib/python2.6/dist-packages/autobahn/websocket/protocol.py", line 842, in onCloseFrame
    call = taxio.call_later(
NameError: global name 'taxio' is not defined

**Comment by meejah** [comment]
This was fixed in #381 and a unit-test added in #384 although it seems there hasn't been a release since those fixes went in :(

**Comment by meejah** [comment]
These fixes are in 0.10.4 so I believe this issue can be closed.
