### ISSUE TITLE
Make it possible to pass an SSLContext instance to asyncio ApplicationRunner

### ISSUE THREAD

**Issue by terrycojones** [tavendo/AutobahnPython#393]
Currently, the `ApplicationRunner` class in `autobahn/asyncio/wamp.py` creates a client connection via

```
loop.create_connection(transport_factory, host, port, ssl=isSecure)
```

where the `isSecure` value is a `bool` based on whether the ws URL scheme is `wss` or not. The [asyncio docs for create_connection](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_connection#creating-connections) also allows the `ssl` to be an `ssl.SSLContext` object, but there is currently no way to pass such an object to the `ApplicationRunner`'s `__init__` method.

One way in which this causes inconvenience is that (at least on Mac OS X with OpenSSL 1.0.2a 19 Mar 2015), a connection cannot be made to a server with a self-signed certificate. An error is thrown, whose traceback ends as follows:

```
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/selector_events.py", line 802, in _on_handshake
    self._sock.do_handshake()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

I have verified that I can make the `wss` connection if I pass an appropriate `SSLContext` to `create_connection`. A context that works is:

```python
import ssl
context = ssl.create_default_context()
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE
```

Being able to do this is very useful for testing, as it allows me to put non-deployment certificates and keys into a public repo, use them in the test suite of my project, etc. This change will also offer others whatever SSL flexibility they might need.

Note that this change is only relevant to the asyncio side of AutobahnPython. Twisted does things differently, and connections to servers with self-signed certificates may already work (though I suspect not due to line 176 in `twisted/wamp.py`, which has `endpoint_descriptor = "ssl:{0}:{1}".format(host, port)` that doesn't allow the passing of additional args, so the default openssl rejection will follow). Anyway, let's solve the issue for the two code paths (asyncio / Twisted) in separate tickets.

**Comment by meejah** [comment]
This is addressed by PR #398 for both asyncio (by terrycojones) and Twisted.

**Comment by oberstet** [comment]
as @meejah mentions, this is implemented now, since the PR was merged

**Comment by diefans** [comment]
According to your documentation at https://autobahn.readthedocs.io/en/latest/wamp/programming.html?highlight=tls#running-subclass-style-components it is recommended to use `autobahn.asyncio.component.run()`. How is it possible to pass a relaxed `SSLContext`?

**Comment by meejah** [comment]
@diefans in the `Component` configuration of the transport, pass it as `tls=` e.g.:

```python
component = Component(
    transports=[
        {
            u"type": u"websocket",
            u"url": u"wss://localhost:8083/ws",
            u"endpoint": {
                u"type": u"tcp",
                u"host": u"localhost",
                u"port": 8083,
                u"tls": SSLContext(...),                                                                                                                   
            },
        },
    ],
)
