### ISSUE TITLE
Improve behavior on muliple register()

### ISSUE THREAD

**Issue by meejah** [tavendo/AutobahnPython#400]
Currently, if you try to `register()` two different procedures on the same endpoint in the same session, your connection is simply dropped.

Perhaps it makes sense to let multiple methods get registered in the same session if the `options=` would have permitted if the sessions were different (e.g. ROUNDROBIN)? Or, we check early enough in the registration process so that we can simply error out the one `register()` instead of dropping the session?

At the very least, the reason for the connection being dropped should appear in the logs.

**Comment by oberstet** [comment]
huh? you get a normal WAMP error when registering ...
