### ISSUE TITLE
API documentation on website is broken

### ISSUE THREAD

**Issue by estan** [tavendo/AutobahnPython#406]
A lot of documentation is currently missing. E.g:

http://autobahn.ws/python/reference/autobahn.twisted.html#autobahn-twisted-wamp

Seems to have happened somewhat recently.

**Comment by meejah** [comment]
Hmm, the deploy must be broken. @oberstet?

In the meantime you should be able go to `./doc` directory and type `make build`. This will create a virtualenv, install some things and build all the docs into `./_build/index.html`.

**Comment by oberstet** [comment]
@meejah it was working before this https://github.com/tavendo/AutobahnPython/commit/f081159f15349dc29a0f2d87222de3dedb3bd9e1#diff-f3644bba251750c9ec4a2361d6cc59eb

**Comment by oberstet** [comment]
@meejah can you undo what you did there?

**Comment by goeddea** [comment]
Should be fixed - just redeployed and the page linked above now has content again.

@meejah - What do I need to do to get the documentation build to run on Windows? Had to use a Ubuntu VM just now.

**Comment by goeddea** [comment]
Hadn't seen @oberstet comment. Second that - build

**Comment by oberstet** [comment]
I have undone above commit ..

**Comment by meejah** [comment]
Hmm, okay. I've never tried on Windows; the above build-changes were what I had to do to get it working on Debian.

@goeddea did you have SCons installed on your Windows machine? (I couldn't get SCons to install in a venv, hence the --system-site-packages)

**Comment by goeddea** [comment]
The failure on Windows was with the virtualenv (which failed to access Python)

**Comment by oberstet** [comment]
I am running Ubuntu 12.04 and it works there .. mmh. Don't know.

**Comment by meejah** [comment]
@goeddea hmm. Do other virtualenv things work on Windows? or maybe it's just a path-thing (like, windows doesn't like the ./venv/bin/python access?) Sorry, mostly shooting in the dark here ;)

**Comment by estan** [comment]
It seems like some documentation, e.g.

    http://autobahn.ws/python/reference/autobahn.asyncio.html#autobahn-asyncio-wamp

is still missing.

Could someone with privileges re-open the issue? (I cannot, as I didn't close it myself).

**Comment by goeddea** [comment]
Trying to build the docs on my machine, I get import errors for the modules for which the documentation is missing:

```shell
/home/gzost/scm/autobahn/AutobahnPython/doc/reference/autobahn.asyncio.rst:12: WARNING: autodoc: failed to import module u'autobahn.asyncio.wamp'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/gzost/scm/autobahn/AutobahnPython/autobahn/asyncio/wamp.py", line 33, in <module>
    from autobahn.asyncio.websocket import WampWebSocketClientFactory
  File "/home/gzost/scm/autobahn/AutobahnPython/autobahn/asyncio/websocket.py", line 40, in <module>
    import trollius as asyncio
  File "/usr/local/lib/python2.7/dist-packages/trollius/__init__.py", line 21, in <module>
    from .coroutines import *
  File "/usr/local/lib/python2.7/dist-packages/trollius/coroutines.py", line 13, in <module>
    from . import events
  File "/usr/local/lib/python2.7/dist-packages/trollius/events.py", line 238, in <module>
    AbstractEventLoop = asyncio.AbstractEventLoop
AttributeError: 'module' object has no attribute 'AbstractEventLoop'
/home/gzost/scm/autobahn/AutobahnPython/doc/reference/autobahn.asyncio.rst:20: WARNING: autodoc: failed to import module u'autobahn.asyncio.websocket'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/gzost/scm/autobahn/AutobahnPython/autobahn/asyncio/websocket.py", line 40, in <module>
    import trollius as asyncio
  File "/usr/local/lib/python2.7/dist-packages/trollius/__init__.py", line 21, in <module>
    from .coroutines import *
  File "/usr/local/lib/python2.7/dist-packages/trollius/coroutines.py", line 12, in <module>
    from . import compat
ImportError: cannot import name compat
```

**Comment by goeddea** [comment]
@meejah @hawkowl - could one of you take a look at this?

**Comment by oberstet** [comment]
fixed: eg http://autobahn.ws/python/reference/autobahn.asyncio.html#autobahn.asyncio.wamp.ApplicationSession
