### ISSUE TITLE
Open ws connection Upgrade: WebSocket header

### ISSUE THREAD

**Issue by kolko** [tavendo/AutobahnPython#408]
I tied to connect to agar.io game.
Server return 400 BadRequest:

connection to tcp:151.80.98.53:1502 established
TX Octets to tcp:151.80.98.53:1502 : sync = False, octets = b'474554202f20485454502f312e310d0a557365722d4167656e743a204175746f6261686e507974686f6e2f302e31302e340d0a486f73743a203135312e38302e39382e35333a313530320d0a557067726164653a20576562536f636b65740d0a436f6e6e656374696f6e3a20557067726164650d0a507261676d613a206e6f2d63616368650d0a43616368652d436f6e74726f6c3a206e6f2d63616368650d0a5365632d576562536f636b65742d4b65793a20395a35304d504c455373435a4d525a34675a315574673d3d0d0a4f726967696e3a20687474703a2f2f616761722e696f0d0a5365632d576562536f636b65742d56657273696f6e3a2031330d0a0d0a'
GET / HTTP/1.1
User-Agent: AutobahnPython/0.10.4
Host: 151.80.98.53:1502
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: 9Z50MPLESsCZMRZ4gZ1Utg==
Origin: http://agar.io
Sec-WebSocket-Version: 13

RX Octets from tcp:151.80.98.53:1502 : octets = b'485454502f312e31203430302042616420526571756573740d0a0d0a'
received HTTP response:

b'HTTP/1.1 400 Bad Request\r\n\r\n'

received HTTP status line in opening handshake : HTTP/1.1 400 Bad Request
received HTTP headers in opening handshake : {}
failing WebSocket opening handshake ('WebSocket connection upgrade failed (400 - BadRequest)')
connection to tcp:151.80.98.53:1502 lost

But other websocket module connect normal:

Connect to 167.114.174.62:1502
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 167.114.174.62:1502
Origin: http://agar.io
Sec-WebSocket-Key: gn/tcQDBSTmTj39Xf8bBNg==
Sec-WebSocket-Version: 13

--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: sU1co3uY9MeO1wR/KaTWkDq2HDI=

send: b'\x81\x83~\xe3\xe2eO\xd1\xd1'
Done!

Found in RFC what Upgrade variable must be case-insensitive, but in rfc variable is in lower-case:
https://tools.ietf.org/html/rfc6455#section-4.2.1
I change header in lower-case in protocol.py and connection success:

connection to tcp:151.80.96.56:1501 established
TX Octets to tcp:151.80.96.56:1501 : sync = False, octets = b'474554202f20485454502f312e310d0a557365722d4167656e743a204175746f6261686e507974686f6e2f302e31302e340d0a486f73743a203135312e38302e39362e35363a313530310d0a557067726164653a20776562736f636b65740d0a436f6e6e656374696f6e3a20557067726164650d0a507261676d613a206e6f2d63616368650d0a43616368652d436f6e74726f6c3a206e6f2d63616368650d0a5365632d576562536f636b65742d4b65793a20624e2f7a686e73474f5a39332b4f5830476b4e3242673d3d0d0a4f726967696e3a20687474703a2f2f616761722e696f0d0a5365632d576562536f636b65742d56657273696f6e3a2031330d0a0d0a'
GET / HTTP/1.1
User-Agent: AutobahnPython/0.10.4
Host: 151.80.96.56:1501
Upgrade: websocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: bN/zhnsGOZ93+OX0GkN2Bg==
Origin: http://agar.io
Sec-WebSocket-Version: 13

RX Octets from tcp:151.80.96.56:1501 : octets = b'485454502f312e312031303120537769746368696e672050726f746f636f6c730d0a557067726164653a20776562736f636b65740d0a436f6e6e656374696f6e3a20557067726164650d0a5365632d576562536f636b65742d4163636570743a205957795458726e3375694c2b6b637074763466456d5564366964343d0d0a0d0a'
received HTTP response:

b'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: YWyTXrn3uiL+kcptv4fEmUd6id4=\r\n\r\n'

received HTTP status line in opening handshake : HTTP/1.1 101 Switching Protocols

Maybe change header Update into lower-case? Many hand-made ws servers may just copy-paste "Upgrade: websocket" match from RFC and do not lower inputs.
I dont know what is agar.io backend and how many servers are not following RFC, but i lost 3 hours last night and do not find answer "why server return BadRequest", next day i try websocket module and it connect! 
If this case can do what with you library you can connect to more (bad) ws-servers - will be good if you change case of Upgrade header. :)

**Comment by oberstet** [comment]
> Maybe change header Update into lower-case? Many hand-made ws servers may just copy-paste "Upgrade: websocket" match from RFC and do not lower inputs.

The solution is for broken implementations to fix.
