### ISSUE TITLE
Why are the examples gone?

### ISSUE THREAD

**Issue by sscirrus** [tavendo/AutobahnPython#417]
Hi guys,

I was actively using the serial2ws example because of the Arduino component and it (and many other examples) seem to have disappeared. Why were they removed from the repo and is there something else I can look at instead?

**Comment by meejah** [comment]
Hi @sscirrus which example?

I recently re-organized the autobahn examples and removed a bunch of the WAMP ones as they used Router-related classes whose functionality is now in Crossbar.io however, perhaps I was overzealous.

Also, I moved things down a directory level so things that were in ``examples/twisted/wamp/basic/*`` are now just in ``examples/twisted/wamp``

**Comment by sscirrus** [comment]
Hi @Meejah, thanks for getting back to me so quickly.

The example I am using was at: https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/app/serial2ws

Be aware also there is at least one important blog post for Arduino that has been affected by the change: http://tavendo.com/blog/post/arduino-yun-with-autobahn/ (I am not affiliated with the article).

**Comment by meejah** [comment]
Ah, I see what's happened -- I intended to move all the "app" examples to the https://github.com/crossbario/crossbarexamples/ repository, but I haven't done that yet.

Perhaps the best thing in the short-term is to restore those examples in Autobahn until they're actually moved to crossbarwww ...

**Comment by sscirrus** [comment]
Sounds good, thanks!

**Comment by meejah** [comment]
Great, thanks again for the bug-report.
cc: @oberstet

**Comment by oberstet** [comment]
@meejah ah yeah. there are interesting exampels in "twisted/wamp/app" we definitely want to preserve. but I agree, these should move to crossbarexamples.

**Comment by oberstet** [comment]
this is fixed
