### ISSUE TITLE
WebSocket server is broken when trollius is used instead of asyncio

### ISSUE THREAD

**Issue by ivan** [tavendo/AutobahnPython#426]
I had a Python 3.4.0 on Ubuntu 14.04 and needed a newer asyncio with `asyncio.ensure_future`, so I installed trollius.  However, using trollius instead of asyncio broke `WebSocketServerProtocol`.  My `onConnect` and `onMessage` methods were never called.

To reproduce this bug, install trollius 2.0, copy https://github.com/tavendo/AutobahnPython/blob/master/examples/asyncio/websocket/echo/server.py and change the imports near the bottom to just `import trollius as asyncio`

Then, start the server.  Connect a WebSocket client and send a few frames.

With the old asyncio import, I saw:

```
# python3 example.py 
Client connecting: tcp:127.0.0.1:42222
WebSocket connection open.
Text message received: sdfasdf
Text message received: asdfasfdasdfasdf
```

With the trollius import, I saw just:                    

```
# python3 example.py
WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
```

```
# python3 --version
Python 3.4.0
```

**Comment by oberstet** [comment]
I have no clue. officially, we don't test and support the Python 3.4 / Trollius combination: http://autobahn.ws/python/installation.html#supported-configurations
