### ISSUE TITLE
If onOpen takes too many arguments, exception is not logged

### ISSUE THREAD

**Issue by ivan** [tavendo/AutobahnPython#427]
If `onOpen` in a `WebSocketClientProtocol` is incorrectly defined as `def onOpen(self, extraArg)` instead of `def onOpen(self)`, autobahn presumably calls `onOpen` with "too few" arguments, but the `TypeError` exception is not logged anywhere.

**Comment by meejah** [comment]
If you set ``debug_wamp=True`` in your ApplicationRunner you will get a traceback.

Logging in general in Autobahn could use some improvements, and this is one of them; this should be logged no matter what (IMO), and get printed out if the appropriate log-level has been previously set.
