### ISSUE TITLE
Provide doc in pypi release

### ISSUE THREAD

**Issue by Jenselme** [tavendo/AutobahnPython#429]
Hi,

Currently, the release of autobahn on pypi doesn't include the doc folder, nor the README. Can you please include them?

**Comment by goeddea** [comment]
Hi!

The documentation files require building using a toolchain (e.g. including sphinx), so in their raw form they would be little use. 

We should look at including a processed version, as well as the readme.

**Comment by Jenselme** [comment]
> We should look at including a processed version, as well as the readme.

Yes, that would be better.

**Comment by meejah** [comment]
I've got a (new) branch that builds the docs inside a virtualenv (and therefore without SCons) but I believe a number of the assets are missing from the repository, e.g. CSS files and probably some images/SVGs I haven't noticed yet. Copy-pasting from the deployed autobahn.ws/python I guess at least these:

```html
   <link rel="stylesheet" href="//tavendo-common-static.s3-eu-west-1.amazonaws.com/css/tavendo.css">
   <link rel="stylesheet" href="//tavendo-common-static.s3-eu-west-1.amazonaws.com/css/autobahn.css">
url(//tavendo-common-static.s3-eu-west-1.amazonaws.com/img/gen/autobahnpython.svg.gz)
//tavendo-common-static.s3-eu-west-1.amazonaws.com/img/gen/autobahn.svg.gz
<img src="//tavendo-common-static.s3-eu-west-1.amazonaws.com/img/gen/we_are_reactive.svg.gz"
```

**Comment by oberstet** [comment]
yep, it doesn't include docs. the docs are online or can be built locally from the repo. no reason to increase the pypi package size ..

**Comment by meejah** [comment]
I meant above: some of the assets (css, svg) required to build locally are missing; this *could* just depend on them being in amazon of course but then not entirely local...

**Comment by oberstet** [comment]
@meejah ah, that's right. the reason is, that the docs are deployed into a bigger site (autobahn.ws) ..
