### ISSUE TITLE
Server recieves but client does not

### ISSUE THREAD

**Issue by zahlio** [tavendo/AutobahnPython#432]
So im running on AWS beanstalk using apache.

I have my autobahn server runinng on port 8080, as an apache proxy to point to that. It looks a something like this:

```
<VirtualHost *:80>
    ServerName websocket.foo.com

    ProxyPass /ws ws://127.0.0.1:8080/ws
    ProxyPassReverse /ws ws://127.0.0.1:8080/ws
</VirtualHost>
```

My server runs fine and when i run it in debug mode i can see when a client enters with the following request:

```
GET /ws/?agent_id=9 HTTP/1.1
Origin: https://app.foo.com
Upgrade: WebSocket
Accept-Language: en-US,en;q=0.8,da;q=0.6
Accept-Encoding: gzip, deflate, sdch
X-Forwarded-Host: websocket.foo.com
X-Forwarded-Port: 443
X-Forwarded-For: x, x
Sec-Websocket-Version: 13
Connection: Upgrade	
Sec-Websocket-Key: kZsC4ekgMyfRhXibwhHzeg==
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36
Host: 127.0.0.1:8080
X-Forwarded-Proto: https
Cookie: __cfduid=d1467ccb6824ee8a59e57cbd245af817a1433702820; _gat=1; _ga=GA1.2.196486585.1433702963
Pragma: no-cache
Cache-Control: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
X-Forwarded-Server: websocket.foo.com
```

The server now wants to send a response:

```
HTTP/1.1 101 Switching Protocols
Server: AutobahnPython/0.10.4
X-Powered-By: AutobahnPython/0.10.4
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: ifFa888u7HRDZgWPYGEhZQkrMhk=
```

This is were i stop understanding what is going on, because the client ends up with the following error code:

```
WebSocket connection to 'wss://websocket.foo.com/ws/?agent_id=9' failed: Error during WebSocket handshake: Unexpected response code: 408

Connection closed (wasClean = false, code = 1006, reason = '')
```

The server however seems to send whatever i tell it to with messages lige these:

```
2015-07-26 01:58:14+0200 [-] TX Frame to tcp4:127.0.0.1:52585 : fin = True, rsv = 0, opcode = 1, mask = -, length = 2, repeat_length = None, chopsize = None, sync = False, payload = []
2015-07-26 01:58:14+0200 [-] TX Octets to tcp4:127.0.0.1:52585 : sync = False, octets = 81025b5d
2015-07-26 01:58:14+0200 [-] TX Frame to tcp4:127.0.0.1:52605 : fin = True, rsv = 0, opcode = 1, mask = -, length = 2, repeat_length = None, chopsize = None, sync = False, payload = []
2015-07-26 01:58:14+0200 [-] TX Octets to tcp4:127.0.0.1:52605 : sync = False, octets = 81025b5d
```

So what is going on?

**Comment by oberstet** [comment]
This is more an APache question. the client gets a HTTP 408 (a timeout) .. I have no clue what Apache is doing here. sorry, we don't use Apache anymore ..

**Comment by zahlio** [comment]
Yeah, changed to docker and started using nginx. Works like a charm.

**Comment by oberstet** [comment]
glad it works for you! using nginx instead of apache: a wise decision;)

**Comment by zahlio** [comment]
Hmm, i went back to this i seem to have the same issue with nginx.

**Comment by oberstet** [comment]
You might try setting the `externalPort` to the external visible port your Nginx is listening on (if that differs from the port of the actual Autobahn WebSocket server behind). Please see [here](http://autobahn.ws/python/reference/autobahn.websocket.html#autobahn.websocket.protocol.WebSocketServerFactory)

**Comment by zahlio** [comment]
We have done that all along :)
