### ISSUE TITLE
No handlers could be found for logger "trollius"

### ISSUE THREAD

**Issue by Budulianin** [tavendo/AutobahnPython#435]
Most likely it's trollius bug, but may be you advise how resolve this issues.

This occur when I try launch example (examples/asyncio/websocket/slowsquare, server_py2.py and client.py)
Issue arise when I launch the client while server_py2.py already launch. Message(No handlers could be found for logger "trollius") appears in console(server_py2.py) and interaction between client and server stops. This behavior doesn't repeat always, but often.

**Comment by oberstet** [comment]
@hawkowl could you have a look?

**Comment by Budulianin** [comment]
Maybe this will be helpful
https://bitbucket.org/enovance/trollius/issues/19/no-handlers-could-be-found-for-logger

**Comment by hawkowl** [comment]
@oberstet can do

**Comment by hawkowl** [comment]
Okay, figured out why.

On py3.4, this would usually raise something and log it. On py2, it does not log it, and it goes unhandled and breaks the execution flow. It happens "often" because of the "if x > 5, raise()" behaviour.

```
red ~/c/A/e/a/w/slowsquare (nohandler-trollius) [1]> python3.4 client.py
Request to square 3.434046344909054 sent.
Result received: 11.792674298983234
red ~/c/A/e/a/w/slowsquare (nohandler-trollius)> python3.4 client.py
Request to square 6.688077872282769 sent.
```

And then it froze.

**Comment by hawkowl** [comment]
This is running 3.4 as the server:

```
Request to square 5.145761737379083 sent.
Exception raised: number too large
```
