### ISSUE TITLE
ApplicationRunner.run return value is wrong

### ISSUE THREAD

**Issue by iffy** [tavendo/AutobahnPython#440]
https://github.com/iffy/AutobahnPython/blob/master/autobahn/twisted/wamp.py#L149

The documentation for `autobahn.twisted.wamp.ApplicationRunner.run` is incorrect.  It states that when `start_reactor=False` the `Deferred` from `connect()` is returned (which results in a protocol instance).  But the code actually returns the result of `reactor.addSystemEventTrigger`.

I've run out of time today to create a failing test case that would ensure the docs are accurate.

**Comment by oberstet** [comment]
oh, I see. this is indeed not a doc bug, but a real bug;)
