### ISSUE TITLE
latest autobahn version breaks on twisted < 12

### ISSUE THREAD

**Issue by tardyp** [tavendo/AutobahnPython#442]
Please see stack trace associated to this PR:
https://github.com/buildbot/buildbot/pull/1808#issuecomment-129131366

We would like to avoid dropping support for twisted < 12, especially as the issue looks pretty trivial.

The problems comes from this pr: #396 which uses non API fro twisted, and that appeared in recent version of twisted.

**Comment by oberstet** [comment]
as @hawkowl already commented, we'll just use `six` in this particular case:

```console
oberstet@thinkpad-t430s:~/scm/autobahn/AutobahnPython$ find autobahn/ -name "*.py" -exec grep -Hi "compat" {} \; | grep import
autobahn/wamp/test/test_protocol.py:    from twisted.python import log, compat
autobahn/twisted/resource.py:from twisted.python.compat import _PY3
autobahn/websocket/test/test_websocket.py:    from twisted.python.compat import _PY3
```

**Comment by hawkowl** [comment]
Yeah -- I'll do up a PR to fix that, unless you get to it before me @oberstet .

**Comment by oberstet** [comment]
@hawkowl @meejah in general: do you think it would make sense to add variants to Tox testing different versions of Twisted? might lead to combinatorical explosion though. and Twisted < 12? really?

**Comment by hawkowl** [comment]
We could test various major versions -- depending on how ancient you want to go back. I wouldn't term 12 as one we really want to support (for one it has dangerously broken TLS support), but 13.2 (version shipped on OSX 10.10), 15.0, and current, might be a good set.

**Comment by oberstet** [comment]
@tardyp if this fixes the issue with Buildbot, and trunk works fine for Buildbot, we can do a quick follow-up release (0.10.5.2) ..

**Comment by tardyp** [comment]
I would appreciate an update, as currently our CI is broken because of this :-}
Our only other option is to force previous version of autobahn in our setup.

Thanks for the quick fix!

**Comment by oberstet** [comment]
@tardyp just released https://pypi.python.org/pypi/autobahn/0.10.5.post2

**Comment by tardyp** [comment]
Thanks. This is very much appreciated. We have seen or Travis builds going
back to normal

Le dim. 9 août 2015 17:15, Tobias Oberstein <notifications@github.com> a
écrit :

**Comment by meejah** [comment]
@oberstet I think it probably makes sense to test the Twisted versions that ship with popular Linux distributions, e.g. Debian stable + testing, LTS versions of Ubuntu, as many sys-admins really don't like to use virtualenvs and so will prefer packaged versions (when available).

It would also make sure that anyone wanting to package autobahn for those distributions will have an easy time...

**Comment by tardyp** [comment]
Yes. This is the reason why buildbot support such old version of twisted.
Travis makes it easy to test them you can look at your travisrc.
