### ISSUE TITLE
Can't use example code with python 2.7

### ISSUE THREAD

**Issue by arnuschky** [tavendo/AutobahnPython#444]
I thought that the example code would work with python2.7 via using Trollius. However, my components cannot connect to my crossbar instance. The same code works fine with python 3.4.

I tested the following examples: http://autobahn.ws/python/wamp/programming.html and examples/asyncio/wamp/pubsub/basic

This is the error I get:

```
python backend.py
Traceback (most recent call last):
  File "backend.py", line 60, in <module>
    runner.run(Component)
  File "/home/user/.pvenvs/autobahn/local/lib/python2.7/site-packages/autobahn/asyncio/wamp.py", line 162, in run
    (transport, protocol) = loop.run_until_complete(coro)
  File "/home/user/.pvenvs/autobahn/local/lib/python2.7/site-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/home/user/.pvenvs/autobahn/local/lib/python2.7/site-packages/trollius/futures.py", line 286, in result
    raise self._exception
trollius.py33_exceptions.ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 8080, 0, 0)
```

I am a total noob at crossbar/autobahn/asyncio, so please let me know if this is either a stupid question or should be addressed to another project/forum.

**Comment by meejah** [comment]
It is not a stupid question ;) but the asyncio examples in the repository are written for Python 3 as they use the "yield from" syntax. I'm presuming you already changed those to plain "yield" from your above report.

It seems that "localhost" resolves to an IPv6-only ("::1") address in Trollius; if I change it to "127.0.0.1" the example works. I'm not sure if this is a Trollius "feature" or local config issue or if we simply shouldn't be using "localhost" -- but if your router is listening on an IPv4 address it won't work. (Note that you can do this via environment variable: ``export AUTOBAHN_DEMO_ROUTER=ws://127.0.0.1:8080/ws``)

I'd like to leave this issue open: we should either replace all the "localhost" references with "127.0.0.1" to ensure IPv4 operation (and reduce ambiguity), and/or upgrade the documentation regarding this.

**Comment by arnuschky** [comment]
Thanks, that was it. Should have seen it from the `::1` in the traceback. Works like a charm now.

**Comment by meejah** [comment]
See #448 which replaces "localhost" in all examples to avoid ambiguity.

**Comment by oberstet** [comment]
#448 was merged now. closing
