### ISSUE TITLE
TypeError: txaio.resolve() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by jcelliott** [tavendo/AutobahnPython#445]
I'm getting this error when trying to unregister an endpoint. Using Python 2.7.10, Autobahn 0.10.5, Trollius 2.0. It's coming from [this line](https://github.com/tavendo/AutobahnPython/blob/master/autobahn/wamp/protocol.py#L889).

Here is the code I used to reproduce it (running against a crossbar router with default settings):

``` python
import trollius as asyncio
from trollius import From
from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner

class MyComponent(ApplicationSession):
    @asyncio.coroutine
    def onJoin(self, details):
        print("session joined")
        def test():
            print("testing")
        registration = yield From(self.register(test, u'app.test'))
        print("registered {} {}".format(registration.procedure, registration.id))
        yield From(asyncio.sleep(1))
        res = yield From(registration.unregister())
        print("unregistered")


if __name__ == '__main__':
    runner = ApplicationRunner(url=u"ws://127.0.0.1:8080/ws", realm=u"realm1", debug_wamp=True)
    runner.run(MyComponent)
```

Is this a bug in Autobahn or something I'm doing wrong?

**Comment by meejah** [comment]
It's actually a bug in ``txaio``, which is missing a default parameter for ``resolve()`` in the asyncio implementation; once https://github.com/tavendo/txaio/pull/6 is merged we can update the dependencies in Autobahn which should fix this.
