### ISSUE TITLE
Exception is raised when Websocket server disconnected

### ISSUE THREAD

**Issue by matusvalo** [tavendo/AutobahnPython#454]
Hi,

I have found out that websocket client (using asyncio backend) is raising exception, when (tornado based) server is disconnected. The issue is appearing in versions 0.10.5-2 and 0.10.5. In the older versions the bug is not appearing.

Here is the stacktrace:

Traceback (most recent call last):
  File "C:\Python27_Dataposting\lib\site-packages\autobahn\asyncio\websocket.py"
, line 97, in connection_lost
    self._connectionLost(exc)
  File "C:\Python27_Dataposting\lib\site-packages\autobahn\websocket\protocol.py
", line 3765, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "C:\Python27_Dataposting\lib\site-packages\autobahn\websocket\protocol.py
", line 1234, in _connectionLost
    txaio.resolve(self.is_closed, self)
AttributeError: '_DataPostingProtocol' object has no attribute 'is_closed'

**Comment by meejah** [comment]
@matusvalo did you derive your "_DataPostingProtocol" from autobahn.websocket.protocol.WebSocketProtocol?

The is_closed future was added in c54d9c35 but that appears to be in 0.10.5-2.

**Comment by matusvalo** [comment]
I am extending WebSocketclientProtocol from autobahn.asyncio.websocket:

from autobahn.asyncio.websocket import WebSocketClientProtocol
class _DataPostingProtocol(WebSocketClientProtocol):

The same usage is in example echo client:

https://github.com/tavendo/AutobahnPython/blob/master/examples/asyncio/websocket/echo/client.py

**Comment by meejah** [comment]
Are you maybe overriding ``__init__`` but not calling the parent? ``self.is_closed`` is created in the constructor...Can you post a minimal failing case (aka "SSCCE") or your actual code?

**Comment by matusvalo** [comment]
@meejah, Thank you. The issue was not calling __init__ of parent. Now it is working fine.

**Comment by immunochomik** [comment]
Yes there is a bug in an example that does not call super in init:
/examples/twisted/websocket/echo_variants/client_with_params.py
