### ISSUE TITLE
Spurious (and misleading) "session is not yet established" error message / exception

### ISSUE THREAD

**Issue by terrycojones** [tavendo/AutobahnPython#459]
I have a `wamp.ApplicationSession` subclass that subscribes to `wamp.session.on_leave`. When the application is exiting, a `ProtocolError` is raised in `wamp/protocol.py`:

```python
raise ProtocolError("Received {0} message, and session is not yet established".format(msg.__class__))
```

This happens because `self._session_id` is `None`. It turns out that the session id is being set to `None` when a `message.Goodbye` is received, but after that happens an event message arrives to notify my app of an `on_leave` event (the one for the app itself). That triggers the `ProtocolError` because `self._session_id` is now `None`). The error message is misleading, because the session was established just fine.

A simple solution might be for the protocol class to set a flag to indicate that a goodbye has been received and to ignore any messages it happens to receive after that point.

**Comment by terrycojones** [comment]
Note that this can be mitigated by unsubscribing from `wamp.session.on_leave` before calling `self.leave()`.

**Comment by meejah** [comment]
So what I believe is going on here is that Goodbye arrives at the router-side, and it immediately sends on the Goodbye and publishes to on_leave. So these both arrive at the other side "at once", so the goodbye gets processed first, and the event causes a ProtocolError. So, I think it's actually a crossbar bug.

We could of course process any event messages received after the Goodbye (or not throw an error) but you shouldn't get messages routed to you after you've left (right?).

**Comment by oberstet** [comment]
this is a crossbar bug https://github.com/crossbario/crossbar/issues/431

**Comment by oberstet** [comment]
@meejah should be fixed in https://github.com/crossbario/crossbar/pull/432
