### ISSUE TITLE
feature required

### ISSUE THREAD

**Issue by a358003542** [tavendo/AutobahnPython#465]
the app below i described by workflow , and i think the workflow combination some activity which is also can be callback by the Center Router.

1. so  that's will be great that the activity can have the workflow concept, and have a state information  which send to the database .

2. the activity need to run and can be callback, is there anyway that we can have a database that memorize the activity real path , and can activate it  .

![1](https://cloud.githubusercontent.com/assets/1977659/9513358/fa3308fc-4cc1-11e5-9c79-f519017b6d04.png)

**Comment by goeddea** [comment]
I think it's unclear from this what exactly you want to achieve. Could you clarify?
