### ISSUE TITLE
ApplicationRunner.run() - extra unicode encode attempt on host string (Python 2.x, Twisted)

### ISSUE THREAD

**Issue by dbarndt** [tavendo/AutobahnPython#470]
I think the following is a bug only on Python 2.x using Twisted.

The following code is in the *autobahn.twisted.wamp.ApplicationRunner.run()* method. The **host** variable is parsed out by the following:

        isSecure, host, port, resource, path, params = parseWsUrl(self.url)

**self.url** is (expected to be) Unicode, so **host** is parsed out as Unicode. Later, however, **host** is passed to the *six.u()* method, and under Python 2.x *six.u()* attempts to encode **host** as Unicode again, resulting in an exception (see last line):

        # if user passed ssl= but isn't using isSecure, we'll never
        # use the ssl argument which makes no sense.
        context_factory = None
        if self.ssl is not None:
            if not isSecure:
                raise RuntimeError(
                    'ssl= argument value passed to %s conflicts with the "ws:" '
                    'prefix of the url argument. Did you mean to use "wss:"?' %
                    self.__class__.__name__)
            context_factory = self.ssl
        elif isSecure:
            from twisted.internet.ssl import optionsForClientTLS
            context_factory = optionsForClientTLS(six.u(host))

Under Python 3.x, *six.u()* just returns the passed in string, so it's probably fine in that case.

**Comment by dbarndt** [comment]
FWIW if the *six.u()* call is removed, I think the import of the *six* module can be removed as well, as that seems to be the only reference to it in the *autobahn.twisted.wamp.py* module.

**Comment by meejah** [comment]
I think it *should* be safe to simply remove it -- but we don't check self.url against six.text_type or unicode, and oddly the Twisted endpoints desire ``str`` for the hostnames, but ``optionsForClientTLS`` demands ``unicode``. (@hawkowl do you know why?)

Perhaps safest would be to check if it's unicode or not already before calling ``optionsForClientTLS``, and if not wrap it in ``six.u``?

**Comment by egwhoi** [comment]
This fix breaks code that passes in the url as a str in Python 2 (rather than as Unicode).
It seems like this could be fixed by adding these lines before the `assert(type(url) == six.text_type)`:
```python
if type(url) == str:
    url = six.u(url)
```
... but it might break Python 3.  (I'm currently running 2, because I'm using Twisted.)  It may also make sense to do the same for the realm.

**Comment by oberstet** [comment]
@egwhoi correct. user code should *always* provide Unicode strings for URIs and realms. We are only going to make this even more strict in upcoming versions.

**Comment by egwhoi** [comment]
How about adding error messages to the assert statements to make this clear?

```python
        assert(type(url) == six.text_type), "url must be a unicode string"
        assert(type(realm) == six.text_type), "realm must be a unicode string"
```

**Comment by oberstet** [comment]
This is something we could and probably should do, yes. If you care, please file an issue. If the other core devs agree, we're gonna address it. I am +1.

**Comment by egwhoi** [comment]
New issue opened, #486.

**Comment by meejah** [comment]
I think it's fine.

I'm guessing that ``optionsForClientTLS`` insists on ``twisted.compat.unicode`` but other endpoint things use ``str`` for hostnames for some historical reason...? (But, I don't know for sure).
