### ISSUE TITLE
Asyncio add_signal_handler function not implemented in windows

### ISSUE THREAD

**Issue by Pasotaku-SnipersCode** [tavendo/AutobahnPython#471]
For Python3 + Asyncio in windows, the "add_signal_handler" function is not implemented (throws NotImplementedError).
Source: asyncio\events.py and https://docs.python.org/3/library/asyncio-eventloop.html#unix-signals

Therefore, ApplicationRunner.run() will throw the error and not run the event loop.

autobahn\asyncio\wamp.py should at least be:
```
try:
    loop.add_signal_handler(signal.SIGTERM, loop.stop)
except NotImplementedError:
    pass  # Ignore if not implemented. Means this program is running in windows.
```

**Comment by meejah** [comment]
What do we need to do to get equivalent handling on Windows? Anything? (That is, if you ctrl-c the program, will the event loop always stop?)

**Comment by erwinkramer** [comment]
related: https://github.com/python/cpython/issues/137863
