### ISSUE TITLE
Should not check external port if not given

### ISSUE THREAD

**Issue by changyuheng** [tavendo/AutobahnPython#495]
In protocol.WebSocketServerProtocol

Even the externalPort=None, it will later being assigned with port. And then the handshaking will check if the externalPort is equal to port.

This is no problem in normal usage. But when there's port forwarding (e.g. ssh tunnel), the externalPort may not the same with port, so the handshaking would fail.

**Comment by oberstet** [comment]
RFC6455 requires to check the port
