### ISSUE TITLE
Cannot import WampWebSocketClientFactory on Windows

### ISSUE THREAD

**Issue by jjmontesl** [tavendo/AutobahnPython#499]
My application uses:

`from autobahn.twisted.websocket import WampWebSocketClientFactory, connectWS`

Which works perfectly on Linux. However, on Windows, this tries to import `process` from `twisted.internet`, which ends up calling select on a Pipe. This fails on Windows with:

```
File "C:\Devel\console-web\consoleweb\mission_adaptor_console\adaptor_console.py", line 17, in <module>
    from autobahn.twisted.wamp import ApplicationSession, ApplicationSessionFactory
  File "C:\Devel\console-web\env275w64\lib\site-packages\autobahn\twisted\wamp.py", line 40, in <module>
    from autobahn.twisted.websocket import WampWebSocketClientFactory
  File "C:\Devel\console-web\env275w64\lib\site-packages\autobahn\twisted\websocket.py", line 42, in <module>
    from autobahn.twisted.util import peer2str
  File "C:\Devel\console-web\env275w64\lib\site-packages\autobahn\twisted\util.py", line 31, in <module>
    from twisted.internet._posixstdio import PipeAddress
  File "C:\Devel\console-web\env275w64\lib\site-packages\twisted\internet\_posixstdio.py", line 16, in <module>
    from twisted.internet import process, error, interfaces
  File "C:\Devel\console-web\env275w64\lib\site-packages\twisted\internet\process.py", line 119, in <module>
    brokenLinuxPipeBehavior = detectLinuxBrokenPipeBehavior()
  File "C:\Devel\console-web\env275w64\lib\site-packages\twisted\internet\process.py", line 107, in detectLinuxBrokenPipeBehavior
    reads, writes, exes = select.select([w], [], [], 0)
select.error: (10038, 'An operation was attempted on something that is not a socket')
```

I've found a similar issue where it was suggested that `twisted.internet.process` should only be imported on Linux (https://twistedmatrix.com/trac/ticket/6894). 

I'm currently stuck and I have only been able to run run this application on Windows by patching that 'detectLinuxBrokenPipeBehavior` method on Twisted, which is not a very good idea.

What are your thoughts? Shall this be patched on Autobahn side?

**Comment by oberstet** [comment]
Ah yeah .. nice. Sorry, there seems to be some smaller amount of fallout, as both Autobahn and Twisted are moving. We'll address it .. not sure where .. @hawkie?

**Comment by meejah** [comment]
I believe it's fixed by this? https://github.com/tavendo/AutobahnPython/commit/8e2a95428b70b697a5b0b04f6502feab5642b5a0

@jjmontesl can you try with master?

**Comment by Tsunami2069** [comment]
@meejah I reverted the Twisted change (that i said on this -> https://github.com/crossbario/crossbar/issues/455 ) and applied the fix you mentioned and it worked, the crossbar started.

So, right now, both fixes seem work (fix on Twisted and on Autobahn).

**Comment by meejah** [comment]
Great, thanks for testing!

The autobahn imports were wrong as they imported from a "private" module instead of the public one.

**Comment by Tsunami2069** [comment]
My pleasure. So i can expect this issue to be fixed soon via a update on Autobahn rather then a update on Twisted, correct?

**Comment by jjmontesl** [comment]
I cannot test with master on this environment but I applied 8e2a954 and it works flawlessly.

So on my side I'll use the manually patched `util.py` version and I'll upgrade as soon as you release a new version.

Thanks a lot for looking into this. Awesome response time.

**Comment by goeddea** [comment]
@meejah - just ran across this myself after updating to Crossbar 0.11. Installing current trunk AutobahnPython fixed it - so let's close this issue.
