### ISSUE TITLE
Deferred of subscribed functions does not seem to be resolved

### ISSUE THREAD

**Issue by rafzi** [tavendo/AutobahnPython#526]
A function is annotated with @subscribe and registered with ApplicationSession.subscribe via a class. This function uses inlineCallbacks to prevent blocking the reactor. The code had an error and was throwing an exception, but there was no way to know about the exception except weird bugs resulting from it.

I assume you do not resolve the future from subscribed functions, because their return value is not relevant. It would be helpful to have the exceptions logged though.

**Comment by meejah** [comment]
Examining the Autobahn code, it should be going through ``_swallow_error`` if invoking the subscribed procedure fails, which should result in a log message. What version are you using? I tried a quick test modifying one of the pubsub examples, and I do see the logs.

**Comment by rafzi** [comment]
This was originally tested in autobahn==0.10.5.post2 but I upgraded to autobahn==0.10.9 and the problem still exists.

    @subscribe(u"xxx.yyy.zzz")
    @inlineCallbacks
    def Foo(self, arg1, arg2, arg3, arg4, _wampDetails=None):

        print("~~~~~~~~~~~~~ THROWING ~~~~~~~~~~~~")
        raise ValueError("test")
        print("not reached")

The logs of the component:

    2015-09-30 14:46:58+0200 [Container   20261] RX WAMP EVENT Message (subscription = 5424380856036860, publication = 4313927426130762, args = [20, 6, 136629100181644320, u'init    '], kwargs = None, publisher = None, topic = None)
    2015-09-30 14:46:58+0200 [Container   20261] ~~~~~~~~~~~~~ THROWING ~~~~~~~~~~~~

**Comment by meejah** [comment]
Running as a container in crossbar master I can repeat this. I moved it to a crossbar bug.
Thanks for the report!
